language: go
dist: xenial

go:
- 1.12.x

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0
  - sh -c "cd c-data-channels && make"

install:
  # Exclude c-data-channels since it uses cgo, it can't be easily installed with go get
  - go get -v -t `go list ./... | grep -v c-data-channels`

script:
  # Since golangci-lint simply passes the paths to go list and go list doesn't know how to exclude packages, 
  # this seems to be the workaround according to https://github.com/golangci/golangci-lint/issues/301#issuecomment-441311986
  - go list -f '{{.Dir}}' ./... | fgrep -v c-data-channels | xargs realpath --relative-to=. | xargs golangci-lint run -v
  - bash .github/assert-contributors.sh
  - bash .github/lint-commit-message.sh
  - bash .github/lint-filename.sh
